redis_config:
  server_addr: 127.0.0.1:6379
  # password: "" # Optional password
  # Timeouts for Redis/DragonflyDB operations in milliseconds
  # heartbeat_timeout_ms: 1000
  # state_update_timeout_ms: 2000
  # cache_write_timeout_ms: 2000
  # stream_read_timeout_ms: 3000
  # publish_timeout_ms: 2000
metric_config:
  enabled: true
